/**
 * Shared component metadata used by build-registry and watch-registry.
 *
 * To add a new component:
 *   1. Create the component file in apps/www/components/ui/<name>.tsx
 *   2. Add an entry here with description, tags, deps, registryDeps
 *   3. Run `pnpm registry:build` (or let `pnpm registry:watch` pick it up)
 */

export const UI_DIR = "apps/www/components/ui"
export const REGISTRY_DIR = "packages/registry/registry"

export const componentMeta = {
  "accordion": {
    description: "A vertically stacked set of interactive headings that each reveal a section of content.",
    tags: ["disclosure", "interactive"],
    baseUIPrimitive: "Accordion",
    deps: ["@base-ui/react"],
    registryDeps: ["utils"],
  },
  "alert-dialog": {
    description: "A modal dialog that interrupts the user with important content and expects a response.",
    tags: ["overlay", "interactive"],
    baseUIPrimitive: "AlertDialog",
    deps: ["@base-ui/react"],
    registryDeps: ["utils", "button"],
  },
  "autocomplete": {
    description: "An input with a list of filtered options that appear as the user types.",
    tags: ["form", "overlay", "interactive"],
    baseUIPrimitive: "Autocomplete",
    deps: ["@base-ui/react", "lucide-react"],
    registryDeps: ["utils", "scroll-area"],
  },
  "avatar": {
    description: "An image element with a fallback for representing the user.",
    tags: ["display", "primitive"],
    baseUIPrimitive: "Avatar",
    deps: ["@base-ui/react"],
    registryDeps: ["utils"],
  },
  "badge": {
    description: "A small status descriptor for UI elements.",
    tags: ["display", "primitive"],
    deps: ["@base-ui/react", "class-variance-authority"],
    registryDeps: ["utils"],
  },
  "breadcrumb": {
    description: "Displays the path to the current resource using a hierarchy of links.",
    tags: ["navigation", "display"],
    deps: [],
    registryDeps: ["utils"],
  },
  "card": {
    description: "A container for grouping related content and actions.",
    tags: ["display", "layout"],
    deps: [],
    registryDeps: ["utils"],
  },
  "button": {
    description: "A clickable element that triggers an action.",
    tags: ["form", "primitive"],
    baseUIPrimitive: "Button",
    deps: ["@base-ui/react", "class-variance-authority"],
    registryDeps: ["utils"],
  },
  "checkbox": {
    description: "A control that allows the user to toggle between checked and unchecked states.",
    tags: ["form", "interactive"],
    baseUIPrimitive: "Checkbox",
    deps: ["@base-ui/react", "lucide-react"],
    registryDeps: ["utils"],
  },
  "collapsible": {
    description: "An interactive component which expands/collapses a panel.",
    tags: ["disclosure", "interactive"],
    baseUIPrimitive: "Collapsible",
    deps: ["@base-ui/react"],
    registryDeps: ["utils"],
  },
  "command": {
    description: "A command palette component for searching and executing actions.",
    tags: ["overlay", "navigation"],
    deps: [],
    registryDeps: ["utils"],
  },
  "combobox": {
    description: "An input combined with a listbox for selecting from a list of options.",
    tags: ["form", "overlay", "interactive"],
    baseUIPrimitive: "Combobox",
    deps: ["@base-ui/react", "lucide-react"],
    registryDeps: ["utils", "button", "input-group"],
  },
  "dialog": {
    description: "A window overlaid on either the primary window or another dialog window.",
    tags: ["overlay", "interactive"],
    baseUIPrimitive: "Dialog",
    deps: ["@base-ui/react", "lucide-react", "class-variance-authority"],
    registryDeps: ["utils", "button"],
  },
  "drawer": {
    description: "A panel that slides in from the edge of the screen.",
    tags: ["overlay", "interactive", "mobile"],
    baseUIPrimitive: "Drawer",
    deps: ["@base-ui/react"],
    registryDeps: ["utils"],
  },
  "dropdown-menu": {
    description: "Displays a menu to the user — such as a set of actions or functions — triggered by a button.",
    tags: ["overlay", "interactive", "navigation"],
    baseUIPrimitive: "Menu",
    deps: ["@base-ui/react", "lucide-react"],
    registryDeps: ["utils"],
  },
  "empty-state": {
    description: "Empty state with icon, title, description, and action.",
    tags: ["block", "feedback"],
    deps: ["class-variance-authority"],
    registryDeps: ["utils"],
  },
  "field": {
    description: "A form field component that provides labeling, description, and validation for form controls.",
    tags: ["form", "layout"],
    baseUIPrimitive: "Field",
    deps: ["@base-ui/react"],
    registryDeps: ["utils"],
  },
  "input": {
    description: "A text input field.",
    tags: ["form", "primitive"],
    baseUIPrimitive: "Input",
    deps: ["@base-ui/react"],
    registryDeps: ["utils"],
  },
  "item": {
    description: "A flexible list item component with media, content, actions, and variants.",
    tags: ["display", "layout", "list"],
    deps: ["@base-ui/react", "class-variance-authority"],
    registryDeps: ["utils", "separator"],
  },
  "input-group": {
    description: "A composite input component with addons, icons, and buttons.",
    tags: ["form", "composite"],
    deps: [],
    registryDeps: ["utils", "button", "input", "textarea"],
  },
  "label": {
    description: "Accessible form label with required indicator.",
    tags: ["form", "primitive"],
    deps: [],
    registryDeps: ["utils"],
  },
  "menubar": {
    description: "A visually persistent menu common in desktop applications providing quick access to commands.",
    tags: ["navigation", "interactive", "overlay"],
    baseUIPrimitive: "Menubar",
    deps: ["@base-ui/react", "lucide-react"],
    registryDeps: ["utils", "dropdown-menu"],
  },
  "navigation-menu": {
    description: "A collection of navigation links with sub-menus that appear on hover.",
    tags: ["navigation", "interactive", "overlay"],
    baseUIPrimitive: "NavigationMenu",
    deps: ["@base-ui/react", "class-variance-authority", "lucide-react"],
    registryDeps: ["utils"],
  },
  "login": {
    description: "Login form with social auth buttons.",
    tags: ["block", "form", "auth"],
    deps: [],
    registryDeps: ["utils", "button", "input", "label"],
  },
  "pagination": {
    description: "Page navigation with first, last, next, and previous buttons.",
    tags: ["navigation", "interactive"],
    deps: ["lucide-react"],
    registryDeps: ["utils", "button"],
  },
  "popover": {
    description: "Displays rich content in a portal, triggered by a button.",
    tags: ["overlay", "interactive"],
    baseUIPrimitive: "Popover",
    deps: ["@base-ui/react"],
    registryDeps: ["utils"],
  },
  "progress": {
    description: "Displays an indicator showing the completion progress of a task.",
    tags: ["display", "feedback"],
    baseUIPrimitive: "Progress",
    deps: ["@base-ui/react"],
    registryDeps: ["utils"],
  },
  "radio-group": {
    description: "A set of checkable buttons where no more than one can be checked at a time.",
    tags: ["form", "interactive"],
    baseUIPrimitive: "RadioGroup + Radio",
    deps: ["@base-ui/react"],
    registryDeps: ["utils"],
  },
  "scroll-area": {
    description: "Augments native scroll functionality for custom, cross-browser styling.",
    tags: ["display", "layout"],
    baseUIPrimitive: "ScrollArea",
    deps: ["@base-ui/react"],
    registryDeps: ["utils"],
  },
  "select": {
    description: "Displays a list of options for the user to pick from — triggered by a button.",
    tags: ["form", "overlay", "interactive"],
    baseUIPrimitive: "Select",
    deps: ["@base-ui/react", "lucide-react"],
    registryDeps: ["utils"],
  },
  "separator": {
    description: "Visually or semantically separates content.",
    tags: ["display", "primitive"],
    baseUIPrimitive: "Separator",
    deps: ["@base-ui/react"],
    registryDeps: ["utils"],
  },
  "skeleton": {
    description: "Loading placeholder with pulse animation.",
    tags: ["display", "feedback"],
    deps: [],
    registryDeps: ["utils"],
  },
  "spinner": {
    description: "An animated loading spinner indicator.",
    tags: ["display", "feedback"],
    deps: ["lucide-react"],
    registryDeps: ["utils"],
  },
  "toggle": {
    description: "A two-state button that can be toggled on or off.",
    tags: ["form", "primitive", "interactive"],
    baseUIPrimitive: "Toggle",
    deps: ["@base-ui/react", "class-variance-authority"],
    registryDeps: ["utils"],
  },
  "toggle-group": {
    description: "A set of two-state buttons grouped together.",
    tags: ["form", "primitive", "interactive"],
    baseUIPrimitive: "ToggleGroup",
    deps: ["@base-ui/react", "class-variance-authority"],
    registryDeps: ["utils", "toggle"],
  },
  "preview-card": {
    description: "A card that appears on hover to preview linked content.",
    tags: ["overlay", "display"],
    baseUIPrimitive: "PreviewCard",
    deps: ["@base-ui/react"],
    registryDeps: ["utils"],
  },
  "number-field": {
    description: "A numeric input with increment and decrement buttons.",
    tags: ["form", "primitive", "interactive"],
    baseUIPrimitive: "NumberField",
    deps: ["@base-ui/react", "class-variance-authority", "lucide-react"],
    registryDeps: ["utils", "label"],
  },
  "slider": {
    description: "An input where the user selects a value from within a given range.",
    tags: ["form", "interactive"],
    baseUIPrimitive: "Slider",
    deps: ["@base-ui/react"],
    registryDeps: ["utils"],
  },
  "switch": {
    description: "A control that allows the user to toggle between checked and not checked.",
    tags: ["form", "interactive"],
    baseUIPrimitive: "Switch",
    deps: ["@base-ui/react"],
    registryDeps: ["utils"],
  },
  "table": {
    description: "Semantic table primitives for displaying data.",
    tags: ["data", "display"],
    deps: [],
    registryDeps: ["utils"],
  },
  "tabs": {
    description: "A set of layered sections of content — known as tab panels — that are displayed one at a time.",
    tags: ["navigation", "interactive"],
    baseUIPrimitive: "Tabs",
    deps: ["@base-ui/react", "class-variance-authority"],
    registryDeps: ["utils"],
  },
  "textarea": {
    description: "A multi-line text input field.",
    tags: ["form", "primitive"],
    deps: [],
    registryDeps: ["utils"],
  },
  "toast": {
    description: "A succinct message that is displayed temporarily.",
    tags: ["overlay", "feedback"],
    baseUIPrimitive: "Toast",
    deps: ["@base-ui/react", "lucide-react"],
    registryDeps: ["utils"],
  },
  "tooltip": {
    description: "A popup that displays information related to an element when focused or hovered.",
    tags: ["overlay", "interactive"],
    baseUIPrimitive: "Tooltip",
    deps: ["@base-ui/react"],
    registryDeps: ["utils"],
  },
}

export function buildEntry(name, content, meta) {
  return {
    name,
    type: "component",
    description: meta.description,
    version: "0.1.0",
    baseUIVersion: ">=1.3.0",
    files: [{
      path: `${name}.tsx`,
      type: "component",
      content,
    }],
    dependencies: {
      required: meta.deps,
      peer: [],
    },
    registryDependencies: meta.registryDeps,
    tags: meta.tags,
    ...(meta.baseUIPrimitive ? { baseUIPrimitive: meta.baseUIPrimitive } : {}),
  }
}
